version: '3.8'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        API_PORT: $API_PORT
    ports:
      - $API_PORT:$API_PORT
